version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: postgres-movieflix
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movieflix
    ports:
      - "5432:5432"