micronaut:
  application:
    name: movieflix
  data:
    pageable:
      default-page-size: 10
#      max-page-size: int
#      sort-ignore-case: boolean
#      sort-parameter-name: string
#      size-parameter-name: string
#      page-parameter-name: string
#      sort-delimiter: java.util.regex.Pattern

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/movieflix`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
#    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

app:
  url: http://localhost:8080