micronaut:
  application:
    name: movieflix

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/movieflix`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    maximum-pool-size: 5
    minimum-idle: 1
    idle-timeout: 10000
    connection-timeout: 20000

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update